name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup nightly Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2022-12-12
        target: wasm32-unknown-unknown
        profile: minimal
        components: rust-src
    - name: Run tests
      working-directory: ./test
      run: |
        npm ci
        npm test
