name: Demo

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup stable Rust
      run: rustup target add wasm32-unknown-unknown
    - name: Setup nightly Rust
      run: rustup toolchain install nightly-2024-08-02 --profile minimal --target wasm32-unknown-unknown --component rust-src
    - name: Build demo
      working-directory: ./demo
      run: |
        npm ci
        npm run build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: demo/dist # The folder the action should deploy.
